spring:
  application:
    name: stock-server

  datasource:
    url: jdbc:oracle:thin:@oracle-onpremise:1521/XEPDB1
    username: STOCK
    password: stock123
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
      encoding: UTF-8

server:
  port: 8082

stock:
  mock:
    enabled: false

kis:
  app-key: ${KIS_APP_KEY}
  app-secret: ${KIS_APP_SECRET}
  base-url: ${KIS_BASE_URL:https://openapivts.koreainvestment.com:29443}
  call-delay-ms: 100